/**
 * ui-data.ts — Industry Profiles & Onboarding Configurations
 *
 * Provides specialized sector configurations, theme palettes, sample copy,
 * and onboarding steps for local business niches.
 */

export interface IndustryProfile {
  id: string;
  name: string;
  emoji: string;
  tagline: string;
  accentBadge: string;
  accentBg: string;
  accentBorder: string;
  accentColor: string;
  sampleVideoTitle: string;
  sampleVideoPoster: string;
  sampleVideoDuration: string;
  sampleProTip: string;
  sampleSubject: string;
  sampleEmailBody: string;
  sampleQrHeadline: string;
  sampleQrSubtext: string;
  sampleRewardHighlight: string;
  copilotPreset: string;
}

export const INDUSTRY_PROFILES: Record<string, IndustryProfile> = {
  dental_health: {
    id: 'dental_health',
    name: 'Dental Offices & Healthcare',
    emoji: '🦷',
    tagline: 'Automated recall cadences, preventive care perks & cosmetic whitening promotions',
    accentBadge: 'bg-teal-50 text-teal-800 border-teal-200',
    accentBg: 'bg-teal-600',
    accentBorder: 'border-teal-500',
    accentColor: '#0D9488',
    sampleVideoTitle: 'Smile Radiance: In-Office Laser Whitening & Hygiene Care (8s)',
    sampleVideoPoster: 'https://images.unsplash.com/photo-1606811841689-23dfddce3e95?w=1200&auto=format&fit=crop&q=80',
    sampleVideoDuration: '0:08',
    sampleProTip: 'Remind patients to avoid staining beverages for 48 hours after whitening to lock in radiant enamel brightness.',
    sampleSubject: '✨ Prioritize Your Smile: $75 Whitening Voucher & Sonic Brush Perk',
    sampleEmailBody: `Dear {{firstName}},\n\nYour oral wellness is our top priority! We have reserved an exclusive $75 in-office laser whitening voucher or preventive hygiene credit for your next checkup.\n\nWatch our quick 8-second care preview below and claim your appointment time online!`,
    sampleQrHeadline: 'Scan & Unlock Your $75 Smile Care Perk',
    sampleQrSubtext: 'Play our 10-second wellness game at reception for instant dental treatment savings.',
    sampleRewardHighlight: '$75 Off Laser Whitening or Sonic Brush Kit',
    copilotPreset: 'Draft a 6-month patient recall email with whitening perks',
  },
  real_estate: {
    id: 'real_estate',
    name: 'Real Estate Agents & Brokers',
    emoji: '🏡',
    tagline: 'Neighborhood drone showcases, staging advice & automated buyer/seller nurturing',
    accentBadge: 'bg-emerald-50 text-emerald-800 border-emerald-200',
    accentBg: 'bg-emerald-600',
    accentBorder: 'border-emerald-500',
    accentColor: '#059669',
    sampleVideoTitle: 'Exclusive Neighborhood Tour: Drone Showcase & Staging Roadmap (9s)',
    sampleVideoPoster: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=1200&auto=format&fit=crop&q=80',
    sampleVideoDuration: '0:09',
    sampleProTip: 'Proper home staging paired with 4K aerial drone tours reduces days on market by 45% and attracts premium qualified buyers.',
    sampleSubject: '🏡 Exclusive Neighborhood Brief: Drone Tour & $500 Closing Credit',
    sampleEmailBody: `Hi {{firstName}},\n\nThinking about making a move or curious about your neighborhood property valuation? We’ve prepared an exclusive comparative market report and a $500 closing credit voucher for you.\n\nTake a quick 9-second aerial drone tour below!`,
    sampleQrHeadline: 'Scan for Instant Property Valuation & $500 Closing Credit',
    sampleQrSubtext: 'Play our interactive buyer/seller game for instant market perks.',
    sampleRewardHighlight: '$500 Closing Credit & Free Drone Valuation',
    copilotPreset: 'Draft an open-house VIP invitation email with market valuation perks',
  },
  contractors: {
    id: 'contractors',
    name: 'General Contractors & Remodeling',
    emoji: '🔨',
    tagline: '3D blueprint renders, seasonal maintenance reminders & estimate re-engagements',
    accentBadge: 'bg-amber-50 text-amber-800 border-amber-200',
    accentBg: 'bg-amber-600',
    accentBorder: 'border-amber-500',
    accentColor: '#D97706',
    sampleVideoTitle: 'Master Craftsmanship: 3D Renovation Design & Quality Build (8s)',
    sampleVideoPoster: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=1200&auto=format&fit=crop&q=80',
    sampleVideoDuration: '0:08',
    sampleProTip: 'Presenting 3D architectural renders during the initial estimation phase accelerates client approval and permit turnaround.',
    sampleSubject: '🔨 Transform Your Home: $250 Remodel Voucher & Free 3D Design',
    sampleEmailBody: `Hello {{firstName}},\n\nReady to bring your dream kitchen, bathroom, or living space to life? Claim your $250 project discount and complimentary 3D architectural render on any remodel scheduled this season.\n\nWatch our quick 8-second craftsmanship overview below!`,
    sampleQrHeadline: 'Scan for $250 Renovation Discount & Free 3D Render',
    sampleQrSubtext: 'Interactive estimate perks for homeowners and property managers.',
    sampleRewardHighlight: '$250 Off Remodel & Free 3D Architectural Render',
    copilotPreset: 'Draft a seasonal home maintenance and kitchen remodel email',
  },
  tattoo_piercing: {
    id: 'tattoo_piercing',
    name: 'Tattoo & Piercing Parlors',
    emoji: '🖋️',
    tagline: 'Custom flash drops, botanical aftercare education & return session booking loops',
    accentBadge: 'bg-slate-100 text-slate-900 border-slate-300',
    accentBg: 'bg-slate-900',
    accentBorder: 'border-slate-800',
    accentColor: '#0F172A',
    sampleVideoTitle: 'Sterile Artistry: Custom Tattoo Session & Flash Gallery Preview (9s)',
    sampleVideoPoster: 'https://images.unsplash.com/photo-1598371839696-5c5bb00bdc28?w=1200&auto=format&fit=crop&q=80',
    sampleVideoDuration: '0:09',
    sampleProTip: 'Applying sterile botanical aftercare in the first 72 hours locks in deep color saturation and protects line clarity.',
    sampleSubject: '🖋️ Flash Artwork Drop: $50 Custom Ink Voucher & Aftercare Kit',
    sampleEmailBody: `Hey {{firstName}},\n\nOur resident artists just dropped an exclusive batch of original flash designs! Claim your $50 custom session voucher and complimentary deluxe vegan aftercare kit.\n\nPreview the studio flash gallery in the 9-second reel below:`,
    sampleQrHeadline: 'Scan Counter to Win Up to $50 Off Your Next Tattoo Session',
    sampleQrSubtext: 'Scratch our digital flash card for instant studio credits.',
    sampleRewardHighlight: '$50 Off Custom Session & Free Botanical Aftercare Kit',
    copilotPreset: 'Draft a weekend flash day promotion email with aftercare tips',
  },
  financial_wealth: {
    id: 'financial_wealth',
    name: 'Financial Advisors & Wealth Managers',
    emoji: '📈',
    tagline: 'Tax-efficient roadmaps, retirement stress tests & executive client appreciation',
    accentBadge: 'bg-indigo-50 text-indigo-800 border-indigo-200',
    accentBg: 'bg-indigo-700',
    accentBorder: 'border-indigo-600',
    accentColor: '#4338CA',
    sampleVideoTitle: 'Strategic Wealth: 3 Pillars of Tax-Efficient Retirement Planning (8s)',
    sampleVideoPoster: 'https://images.unsplash.com/photo-1450133064473-71024230f91b?w=1200&auto=format&fit=crop&q=80',
    sampleVideoDuration: '0:08',
    sampleProTip: 'Annual beneficiary audits and tax bracket diversification safeguard family wealth from unexpected probate hurdles.',
    sampleSubject: '📈 Safeguard Your Future: Complimentary Retirement Blueprint & Fee Rebate',
    sampleEmailBody: `Dear {{firstName}},\n\nAre your investments optimized for changing tax laws and market volatility? We invite you to an exclusive portfolio stress-test session with a $150 advisory fee credit.\n\nWatch our 8-second wealth briefing below to learn more:`,
    sampleQrHeadline: 'Scan for Your Complimentary Wealth & Tax Blueprint',
    sampleQrSubtext: 'Interactive executive assessment perks for valued clients.',
    sampleRewardHighlight: '$450 Value Retirement Blueprint & $150 Advisory Fee Rebate',
    copilotPreset: 'Draft an annual portfolio review & tax optimization email',
  },
  salon_barber: {
    id: 'salon_barber',
    name: 'Barbershops, Hair Salons & Spas',
    emoji: '✂️',
    tagline: '4-week automated precision rebooking, scalp treatment perks & style drops',
    accentBadge: 'bg-rose-50 text-rose-800 border-rose-200',
    accentBg: 'bg-rose-600',
    accentBorder: 'border-rose-500',
    accentColor: '#E11D48',
    sampleVideoTitle: 'Master Styling & Cut: Precision Fades, Balayage & Scalp Spa (9s)',
    sampleVideoPoster: 'https://images.unsplash.com/photo-1560066984-138dadb4c035?w=1200&auto=format&fit=crop&q=80',
    sampleVideoDuration: '0:09',
    sampleProTip: 'Maintaining a 4-week cadence preserves fade geometry and ensures healthy botanical scalp rejuvenation.',
    sampleSubject: '✂️ Fresh Style Alert: $25 Styling Voucher + Free Scalp Steam',
    sampleEmailBody: `Hey {{firstName}},\n\nIt’s time to refresh your look! We’ve credited your client profile with a $25 styling voucher and a complimentary deep botanical scalp treatment for your next appointment.\n\nWatch our 9-second styling clip below:`,
    sampleQrHeadline: 'Scan Mirror Standee to Win Up to $25 Off Today’s Service',
    sampleQrSubtext: 'Play our 5-second reward game while getting styled!',
    sampleRewardHighlight: '$25 Off Precision Cut/Color & Free Scalp Spa Steam',
    copilotPreset: 'Draft a 4-week haircut rebooking email with scalp massage perk',
  },
  cafe: {
    id: 'cafe',
    name: 'Cafes & Bakeries / Coffee Shops',
    emoji: '☕',
    tagline: 'Morning rush loyalty, fresh pastry drops & artisan single-origin tastings',
    accentBadge: 'bg-amber-50 text-amber-900 border-amber-300',
    accentBg: 'bg-amber-700',
    accentBorder: 'border-amber-600',
    accentColor: '#B45309',
    sampleVideoTitle: 'Artisan Coffee Roasting & Fresh Daily Scratch Bakery (8s)',
    sampleVideoPoster: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=1200&auto=format&fit=crop&q=80',
    sampleVideoDuration: '0:08',
    sampleProTip: 'Pair single-origin pour-overs with slow-fermented croissants baked fresh every morning at 6:30 AM.',
    sampleSubject: '☕ Morning Fuel: Free Specialty Latte & $10 Fresh Pastry Box',
    sampleEmailBody: `Hi {{firstName}},\n\nYour morning brew is on us! Enjoy a complimentary handcrafted artisan latte or $10 off a fresh bakery box on your next morning cafe stop.\n\nWatch our 8-second roast & pastry reel below!`,
    sampleQrHeadline: 'Scan Counter to Win a Free Specialty Latte or Pastry',
    sampleQrSubtext: 'Tap your phone at the coffee bar for instant loyalty perks.',
    sampleRewardHighlight: 'Free Handcrafted Latte or 4oz Roasted Bean Bag',
    copilotPreset: 'Draft a weekend morning bakery drop & coffee tasting email',
  },
  retail: {
    id: 'retail',
    name: 'Retail & Boutiques',
    emoji: '🛍️',
    tagline: 'New collection drops, in-store VIP shopping events & flash promotions',
    accentBadge: 'bg-orange-50 text-orange-800 border-orange-200',
    accentBg: 'bg-orange-600',
    accentBorder: 'border-orange-500',
    accentColor: '#EA580C',
    sampleVideoTitle: 'New Season Arrivals & Boutique Styling Showcase (9s)',
    sampleVideoPoster: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=1200&auto=format&fit=crop&q=80',
    sampleVideoDuration: '0:09',
    sampleProTip: 'New seasonal items have limited runs — encourage customers to reserve online or shop in-store this weekend.',
    sampleSubject: '🛍️ VIP Exclusive: $25 Off New Arrivals + Free Shopping Gift',
    sampleEmailBody: `Hi {{firstName}},\n\nOur new seasonal collection has officially arrived! As a valued VIP customer, enjoy $25 off any purchase of $75+ and a curated gift bag.\n\nWatch our 9-second boutique showcase below!`,
    sampleQrHeadline: 'Scan Register Card for $25 In-Store Shopping Credit',
    sampleQrSubtext: 'Play our quick scratch game for instant checkout savings.',
    sampleRewardHighlight: '$25 Off In-Store Purchase of $75+ & Free VIP Gift',
    copilotPreset: 'Draft a new seasonal collection arrival VIP announcement email',
  },
  fitness: {
    id: 'fitness',
    name: 'Fitness Studios & Wellness',
    emoji: '💪',
    tagline: '1-on-1 coaching assessments, class pack promotions & recovery lounge perks',
    accentBadge: 'bg-cyan-50 text-cyan-800 border-cyan-200',
    accentBg: 'bg-cyan-600',
    accentBorder: 'border-cyan-500',
    accentColor: '#0891B2',
    sampleVideoTitle: 'Studio Quick Start: Form Tips, Recovery & Fast Results (10s)',
    sampleVideoPoster: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=1200&auto=format&fit=crop&q=80',
    sampleVideoDuration: '0:10',
    sampleProTip: 'Hydrate 30 minutes before workout sessions and schedule infrared sauna recovery slots early.',
    sampleSubject: '💪 Coach’s Brief: Free 1-on-1 Training Session & Recovery Pass',
    sampleEmailBody: `Hey {{firstName}},\n\nReady to crush your fitness milestones? Claim your complimentary 1-on-1 training assessment and infrared sauna recovery lounge pass.\n\nWatch our 10-second coach movement brief below:`,
    sampleQrHeadline: 'Scan Front Desk to Win a Free 1-on-1 Session ($85 Value)',
    sampleQrSubtext: 'Unlock instant class credits and recovery lounge passes.',
    sampleRewardHighlight: '$85 1-on-1 Coaching Session & Free Recovery Lounge Pass',
    copilotPreset: 'Draft a 30-day fitness challenge and personal training email',
  },
  services: {
    id: 'services',
    name: 'Professional & Personal Services',
    emoji: '💼',
    tagline: 'Dedicated consultation roadmaps, service upgrades & loyalty incentives',
    accentBadge: 'bg-violet-50 text-violet-800 border-violet-200',
    accentBg: 'bg-violet-600',
    accentBorder: 'border-violet-500',
    accentColor: '#7C3AED',
    sampleVideoTitle: 'Service Excellence: Consultation Roadmap & Session Prep (8s)',
    sampleVideoPoster: 'https://images.unsplash.com/photo-1521791136064-7986c2920216?w=1200&auto=format&fit=crop&q=80',
    sampleVideoDuration: '0:08',
    sampleProTip: 'Have intake preferences prepared in advance to maximize dedicated face-to-face appointment time.',
    sampleSubject: '💼 Consultation Upgrade: $35 Service Credit & Priority Intake',
    sampleEmailBody: `Dear {{firstName}},\n\nWe look forward to collaborating with you! Please enjoy a $35 credit toward your scheduled service appointment and complimentary priority intake.\n\nWatch our 8-second preparation guide below:`,
    sampleQrHeadline: 'Scan for $35 Service Credit & Complimentary Upgrades',
    sampleQrSubtext: 'Interactive loyalty rewards for valued service clients.',
    sampleRewardHighlight: '$35 Service Credit & Free Consultation Report',
    copilotPreset: 'Draft an appointment confirmation and priority consultation email',
  },
  general: {
    id: 'general',
    name: 'General Local Business',
    emoji: '🌟',
    tagline: 'Universal guest engagement, dynamic QR loyalty & automated retention',
    accentBadge: 'bg-amber-50 text-brand-clay border-amber-200',
    accentBg: 'bg-brand-amber',
    accentBorder: 'border-brand-amber',
    accentColor: '#D97706',
    sampleVideoTitle: 'Welcome to VIP Rewards: Unlocking Local Perks & Savings (8s)',
    sampleVideoPoster: 'https://images.unsplash.com/photo-1556742049-0a67e5572293?w=1200&auto=format&fit=crop&q=80',
    sampleVideoDuration: '0:08',
    sampleProTip: 'Display counter standees right next to the POS terminal where customers have 20–30 seconds of natural dwell time.',
    sampleSubject: '🌟 VIP Welcome: $20 Off Your Bill + Exclusive Customer Perks',
    sampleEmailBody: `Hi {{firstName}},\n\nThank you for supporting our local business! As a VIP member, enjoy $20 off your total bill and special perks on every visit.\n\nWatch our 8-second VIP rewards guide below:`,
    sampleQrHeadline: 'Scan Counter to Win $20 Off Your Total Bill Today',
    sampleQrSubtext: 'Play our 5-second customer game for instant savings.',
    sampleRewardHighlight: '$20 Off Total Bill & Complimentary Welcome Gift',
    copilotPreset: 'Draft a VIP customer appreciation email with $20 voucher',
  },
};

export interface OnboardingBubbleStep {
  stepNumber: number;
  badge: string;
  title: string;
  description: string;
  targetTab: string;
  highlightId?: string;
  actionText: string;
}

export const ONBOARDING_STEPS: OnboardingBubbleStep[] = [
  {
    stepNumber: 1,
    badge: '1 of 5 • Sector Setup',
    title: 'Select Your Business Niche',
    description: 'Switch between Dental, Real Estate, General Contractors, Tattoo & Piercing, Financial Wealth, Barbershops & Salons, Cafes & Bakeries, or Retail. The entire platform dynamically adapts its video presets, gamified rewards, and email copy!',
    targetTab: 'video',
    highlightId: 'globalBizCategory',
    actionText: 'Next: Explore Video Studio →',
  },
  {
    stepNumber: 2,
    badge: '2 of 5 • AI Video Engine',
    title: 'Generate 7–10s Promotional Videos',
    description: 'Create high-converting email clips in 16:9 Widescreen (desktop newsletters) or 9:16 Vertical (mobile clients). Powered by MiniMax and HeyGen connectors with 1-click HTML embed copy.',
    targetTab: 'video',
    highlightId: 'btnGenerateVideo',
    actionText: 'Next: Engagement Games →',
  },
  {
    stepNumber: 3,
    badge: '3 of 5 • Lead Capture',
    title: 'Deploy 4 Interactive Games & QR Codes',
    description: 'Turn foot traffic and walk-ins into verified email leads using Scratch Cards, Mystery Boxes, Triple Match Slots, and Memory Flip. Generate ready-to-print countertop standees in seconds!',
    targetTab: 'games',
    highlightId: 'tabBtn-games',
    actionText: 'Next: Dispatch & Anti-Spam →',
  },
  {
    stepNumber: 4,
    badge: '4 of 5 • Deliverability',
    title: 'Audit & Dispatch Outbound Emails',
    description: 'Test email spam score, verify SPF/DKIM authentication, attach video players, and dispatch securely via Resend, SendGrid, or custom SMTP with zero promo abuse.',
    targetTab: 'dispatch',
    highlightId: 'tabBtn-dispatch',
    actionText: 'Next: Automation Pipelines →',
  },
  {
    stepNumber: 5,
    badge: '5 of 5 • Retention Cadence',
    title: 'Activate Automated Rebooking Workflows',
    description: 'Run automated +2hr Gratitude Loops, 15-msg/hour Slow Drips, and 4-to-6 week rebooking cadences with the Gemini Marketing Co-Pilot guiding your strategy.',
    targetTab: 'workflows',
    highlightId: 'tabBtn-workflows',
    actionText: '🎉 Finish Tour & Launch Hub',
  },
];
